epochs: 100000
device: cuda:0
log_dir: /data/sam/bf-nn
init: random-positive-init
loss_func: l1_regularized_loss
model_configs: model-configs/skipbf-cfgs/w64-d-2.yml
layer_type: SingleSkipBFModel
dataset_sizes: 4
eta: 1.0 5.0 10.0
perturb: 1
lr: 0.001
search_eta_lr: 1
dataset_type: construct_ktrain_extended