epochs: 2000000
device: cuda:3
log_dir: /data/sam/bf-nn
init: random-positive-init
loss_func: mean_squared_error_loss
model_configs: model-configs/skipbf-cfgs/w64-d-2.yml
layer_type: SingleSkipBFModel
dataset_sizes: 16
eta: 0.1 0.5 1.0
perturb: 1
lr: 0.001
search_eta_lr: 1
dataset_type: path_2_3_dataset