epochs: 100000
device: cuda:6
log_dir: /data/sam/bf-nn
init: random-positive-init
loss_func: l05_regularized_loss
model_configs: model-configs/configs4.yaml
layer_type: BFModel
dataset_sizes: 16 32 48 128 256 150
eta: 0.20 0.40 0.60 0.80 1.0 0.002 0.005 0.30 0.50 0.70 0.90 1.0 1.1 1.2 1.3
perturb: 1
lr: 0.001
search_eta_lr: 1
