epochs: 100000
device: cuda:0
log_dir: /data/sam/bf-nn
init: random-positive-init
loss_func: mean_squared_error_loss
model_configs: model-configs/configs4.yaml
layer_type: BFModel
dataset_sizes: 4 16 64
eta: 0.01
perturb: 1
lr: 0.01
