epochs: 100000
device: cuda:3
log_dir: /data/sam/bf-nn
init: random-positive-init
loss_func: l1_regularized_loss
model_configs: model-configs/configs4.yaml
layer_type: BFModel
dataset_sizes: 4 16 64
eta: 0.001
perturb: 1
lr: 0.001
search_eta_lr: 1