epochs: 100000
device: cuda:1
log_dir: /data/sam/bf-nn
init: random-init
loss_func: l1_regularized_loss
model_configs: model-configs/w-128-config.yaml
layer_type: BFModel
dataset_sizes: 32
eta: 0.1
perturb: 1
lr: 0.001
search_eta_lr: 1
dataset_type: path_2_3_dataset